spring:
  application:
    name: springboot-enterprise-crud-system

  datasource:
    url: jdbc:postgresql://localhost:5432/enterprise_app
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # or 'validate', 'create', 'none' depending on your need
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
